Repository kampfires/kubefeed, pull requests merged in 2020-02, with the labels that each got.

#1 added tmc manifest
  manifests/readme.md
  manifests/tmc-manifest.yml
Labels: approved, size/XL

#2 On branch add-formio
  manifests/formio-claim0-persistentvolumeclaim.yaml
  manifests/formio-deployment.yaml
  manifests/formio-service.yaml
  manifests/mdb-data-persistentvolumeclaim.yaml
  manifests/mongo-deployment.yaml
Labels: approved, size/L

#4 On branch remove-formio
  delete/formio-claim0-persistentvolumeclaim.yaml
  delete/formio-deployment.yaml
  delete/formio-service.yaml
  delete/mdb-data-persistentvolumeclaim.yaml
  delete/mongo-deployment.yaml
  jenkins-x.yml
Labels: approved, size/XS

#5 test
  delete/formio-claim0-persistentvolumeclaim.yaml
  delete/formio-deployment.yaml
  delete/formio-service.yaml
  delete/mdb-data-persistentvolumeclaim.yaml
  delete/mongo-deployment.yaml
  jenkins-x.yml
  pipescripts/mergetopr.sh
  pipescripts/post-merge-run.sh
  pipescripts/post-pr-run.sh
Labels: approved, size/L

#6 Remove formio
  manifests/formio-service.yaml
  pipescripts/post-pr-run.sh
Labels: approved, size/S

#7 test
  delete/formio-service.yaml
  pipescripts/post-pr-run.sh
Labels: approved, size/XS

#8 test
  jenkins-x.yml
  noodle
  pipescripts/post-pr-run.sh
  test.test
  test2
  test3
Labels: size/S

#10 Rmformsvc
  pipescripts/installhub.sh
  pipescripts/kubedelete.sh
  pipescripts/mergetopr.sh
  pipescripts/post-pr-run.sh
Labels: approved, size/S

#12 test617
  delete/test617
  pipescripts/post-pr-run.sh
  test.503
Labels: approved, size/S

#13 Test617
  pipescripts/post-pr-run.sh
Labels: approved, size/M

#14 Test617
  delete/test.test
  delete/test2
  delete/test3
  delete/test617
  pipescripts/post-pr-run.sh
Labels: approved, size/XS

#16 testdelete752
  manifests/formio-service.yaml
Labels: approved, size/S

#17 cleanup
  README.md
  noodle
  pipescripts/installhub.sh
  pipescripts/kubedelete.sh
  pipescripts/mergetopr.sh
Labels: approved, size/S

#18 cleanup1055
  skaffold.yaml
Labels: approved, size/S
